apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sphinx-coininfo-npool-top-ingress
  namespace: kube-system
  annotations:
    k8s.kuboard.cn/displayName: sphinx-coininfo
    k8s.kuboard.cn/workload: sphinx-coininfo
    kubernetes.io/ingress.class: "traefik-internet"
spec:
  rules:
  - host: api.npool.top
    http:
      paths:
      - path: /sphinx-coininfo
        backend:
          serviceName: sphinx-coininfo
          servicePort: http

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sphinx-coininfo-xpool-top-ingress
  namespace: kube-system
  annotations:
    k8s.kuboard.cn/displayName: sphinx-coininfo
    k8s.kuboard.cn/workload: sphinx-coininfo
    kubernetes.io/ingress.class: "traefik-internet"
spec:
  rules:
  - host: api.xpool.top
    http:
      paths:
      - path: /sphinx-coininfo
        backend:
          serviceName: sphinx-coininfo
          servicePort: http
